version: '3.9'

services:
  web:
    image: vishwacloudlab/stackdemo
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:

    image: redis:7-alpine
    container_name: redis